# Generated by Django 5.1.6 on 2025-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals_app", "0002_transactiontestmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="TestModel",
            new_name="SynchronousTestModel",
        ),
    ]
